### ISSUE TITLE
configurable error with pytorch bottleneck profiler 

### ISSUE THREAD

**Issue by mnoukhov** [google/gin-config#24]
Running pytorch's bottleneck profiler if your script has gin configurables causes an error
`RuntimeError: Attempted to add a new configurable after the config was locked.` or `ValueError: A configurable matching 'some.configurable.module' already exists.`

It seems that the profiler runs the script twice using `exec`, once for `cprofile` and once for the autograd profiler (https://github.com/pytorch/pytorch/blob/1aae4b02df797f98239fde511575c96b8d6806da/torch/utils/bottleneck/__main__.py#L210) and on the second run, my guess is that gin tries to recreate configs that already exist, causing this error.

This is a pretty niche problem and it's possible for someone to just run `cprofile` and the `autograd` profiler separately but I was wondering if there could be a simple workaround. Is there a way to either reset the configurables created (which could be put at the end of the script), somehow ignore errors, or some other workaround you see? Thanks

Here's a minimal snippet
```python
import gin


@gin.configurable
def main(word):
    print(f'hello {word}')

if __name__ == '__main__':
    main('world')
```
when run with `python -m torch.utils.bottleneck script.py` gives the output

```
Running environment analysis...
Running your script with cProfile
hello world
Running your script with the autograd profiler...
Traceback (most recent call last):
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 231, in <module>
    main()
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 210, in main
    autograd_prof_cpu, autograd_prof_cuda = run_autograd_prof(code, globs)
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 102, in run_autograd_prof
    result = [run_prof(use_cuda=False)]
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/torch/utils/bottleneck/__main__.py", line 98, in run_prof
    exec(code, globs, None)
  File "torchgin.py", line 4, in <module>
    @gin.configurable
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/gin/config.py", line 1129, in configurable
    return perform_decoration(decoration_target)
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/gin/config.py", line 1126, in perform_decoration
    return _make_configurable(fn_or_cls, name, module, whitelist, blacklist)
  File "/home/mnoukhov/miniconda3/envs/selfish/lib/python3.7/site-packages/gin/config.py", line 891, in _make_configurable
    raise ValueError(err_str.format(selector))
ValueError: A configurable matching '__main__.main' already exists.
```
I'm running `pytorch 1.1.0` and `gin-config 0.1.4`

**Comment by mnoukhov** [comment]
After a little bit of digging I found that the issue was the config being full (solved by `gin.clear_config`) but also certain functions already being registered (solved by `gin.config._REGISTRY.clear()`) so for my example a quick workaround would be  

```python
import gin

@gin.configurable
def main(word):
    print(f'hello {word}')

if __name__ == '__main__':
    gin.parse_config_file('path/to/config.gin')
    main('world')
    gin.clear_config()
    gin.config._REGISTRY.clear()
```
but it seems that functions from files imported by the main file are not re-registered on the second run e.g.

`mylib.py`
```python
@gin.configurable
def myfunc(word):
    print(f'hello {word}')
```
`script.py`
```python
import gin
from mylib import myfunc

@gin.configurable
def main():
    myfunc()

if __name__ == '__main__':
    gin.parse_config_file('script.gin')
    main()
    gin.clear_config()
    gin.config._REGISTRY.clear()
```
`script.gin`
```
myfunc.word = "world"
```

when run with `python -m torch.utils.bottleneck script.py` fails with 
```
ValueError: No configurable matching 'myfunc'.
  In file "script.gin", line 1
    myfunc.word = "world"
```

So the correct solution seems to be to remove from `_REGISTRY` only the configurables that are in the main script file which for this specific file would look like 

`script.py`
```python
import gin
from mylib import myfunc

@gin.configurable
def main():
    myfunc()

if __name__ == '__main__':
    gin.parse_config_file('script.gin')
    main()
    gin.clear_config()
    gin.config._REGISTRY._selector_map.pop('__main__.main')
```

There is probably a nicer and cleaner way to do this, but really this is all just a workaround for a very specific use-case so I'm going to close the issue since this solution works for me
