### ISSUE TITLE
Using TensorFlow backend. Traceback (most recent call last):   File "Adonia5.py", line 297, in <module>     gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=MEMORY_FRACTION) AttributeError: module 'tensorflow' has no attribute 'GPUOptions'  C:\CarlaProject\PythonAPI\examples>python Adonia5.py Using TensorFlow backend. WARNING:tensorflow:From C:\Users\Hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version. Instructions for updating: non-resource variables are not supported in the long term Traceback (most recent call last):   File "Adonia5.py", line 297, in <module>     tf.random.set_seed(1) AttributeError: module 'tensorflow_core.compat.v1.random' has no attribute 'set_seed'

### ISSUE THREAD

**Issue by AdoniaMbarebaki** [google/gin-config#44]

**Comment by sguada** [comment]
TensorFlow backend. Traceback (most recent call last): File "Adonia5.py", line 297, in <module> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=MEMORY_FRACTION) AttributeError: module 'tensorflow' has no attribute 'GPUOptions' C:\CarlaProject\PythonAPI\examples>python Adonia5.py Using TensorFlow backend. WARNING:tensorflow:From C:\Users\Hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version. Instructions for updating: non-resource variables are not supported in the long term Traceback (most recent call last): File "Adonia5.py", line 297, in <module> tf.random.set_seed(1) AttributeError: module 'tensorflow_core.compat.v1.random' has no attribute 'set_seed', how do i solve this issue while using carla simulator to test reinforcement learning in autonomous cars

**Comment by sguada** [comment]
It seems an error in your code.

**Comment by AdoniaMbarebaki** [comment]
> It seems an error in your code.

Thanks for the reply, am still getting Runtime errors while running carla simulator using the reinforcement learning code as shown below.

C:\CarlaProject\PythonAPI\examples>python Adonia5.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From C:\Users\Hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-01-11 15:25:49.021818: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "Adonia5.py", line 308, in <module>
    env = CarEnv()
  File "Adonia5.py", line 113, in __init__
    self.client = carla.Client("localhost", 2000)
RuntimeError: resolve: The requested name is valid, but no data of the requested type was found.: The requested name is valid, but no data of the requested type was found.
