### ISSUE TITLE
Python 3.7 throws error "future feature google_type_annotations is not defined"

### ISSUE THREAD

**Issue by essandess** [google/gin-config#77]
> `$ python3 -c 'import sys; print(sys.version); import gin'`
```
3.7.7 (default, Mar 14 2020, 02:39:38) 
[Clang 11.0.0 (clang-1100.0.33.17)]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gin/__init__.py", line 17, in <module>
    from gin.config import add_config_file_search_path
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gin/config.py", line 87
    from __future__ import google_type_annotations
    ^
SyntaxError: future feature google_type_annotations is not defined
```

**Comment by IuliiaSaveleva** [comment]
I have the same problem with Python 3.7.1 and 3.8.1(
