### ISSUE TITLE
Unable to pickle objects bound by `.. = @SomeClass()`

### ISSUE THREAD

**Issue by Avsecz** [google/gin-config#8]
I'm unable to pickle objects that were assigned to the function argument using the following synthax`... = @SomeClass()`.

Consider the following script:

```python
import pickle
import gin


@gin.configurable
class Example:
    def __init__(self, a):
        self.a = a

    def __call__(self):
        print("hello", self.a)
        print("Pickle:")
        print(pickle.dumps(self))


@gin.configurable
def say_hello(example):
    print("in function say_hello")
    example()


if __name__ == '__main__':
    gin.parse_config_files_and_bindings(config_files=[],
                                        bindings=['say_hello.example = @Example()',
                                                  'Example.a = 1'])
    e = Example()
    e()
    say_hello()
```

When I run it, I get the following error:
```
 python script.py
hello 1
Pickle:
b'\x80\x03c__main__\nExample\nq\x00)\x81q\x01}q\x02X\x01\x00\x00\x00aq\x03K\x01sb.'
in function say_hello
hello 1
Pickle:
Traceback (most recent call last):
  File "script.py", line 28, in <module>
    say_hello()
  File "/opt/modules/i12g/anaconda/3-5.0.1/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/opt/modules/i12g/anaconda/3-5.0.1/lib/python3.6/site-packages/gin/utils.py", line 48, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/opt/modules/i12g/anaconda/3-5.0.1/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "script.py", line 19, in say_hello
    example()
  File "script.py", line 13, in __call__
    print(pickle.dumps(self))
_pickle.PicklingError: Can't pickle <class '__main__.Example'>: it's not the same object as __main__.Example
  In call to configurable 'say_hello' (<function say_hello at 0x7f92c765de18>)
```

You can see that the first instance of `Example` could be correctly pickled whereas the second one, bounded to `say_hello.example` argument, couldn't. Any ideas on how to solve this issue? I'm using the recent gin-config package from PyPI (0.1.2) on python 3.6.8.

**Comment by Avsecz** [comment]
I was able to pickle the object using `cloudpickle`.

**Comment by piojanu** [comment]
@Avsecz can you tell me what version of cloudpickle and gin-config worked for you? This code doesn't work:

```
import cloudpickle
import gin

@gin.configurable
class Foo:
    def pickle_me(self):
        return cloudpickle.dumps(self)
foo = Foo()
foo.pickle_me()
```

It rises: `TypeError: can't pickle _thread.lock objects`.

This won't work either:

```
@gin.configurable
class Bar:
    pass
cloudpickle.dumps(Bar)
```

Python 3.6, cloudpickle 1.2.2, gin-config 0.2.1.

**Comment by Avsecz** [comment]
Your script works for me with: python 3.6, cloudpickle 0.5.6 and gin-config 0.1.2. 

For python 3.6, cloudpickle 1.2.2 and gin-config 0.2.1, I had to add a special Lock object to `gin.config._OPERATIVE_CONFIG_LOCK` before running `return cloudpickle.dumps(self)`. See the following code example: https://github.com/kundajelab/bpnet/blob/db8908e068034387b77bcc7c358a8172f40ed132/bpnet/seqmodel.py#L331-L337

**Comment by piojanu** [comment]
I'll give it a shot! Thanks :)
